name: Phoebus Tecnologia CI/CD with Github Actions

on:
    push:
        branches: ["*"]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Node-setup
        uses: actions/setup-node@v1
        with:
          node-version: 16

      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v4.2.0
        with:
          build: npm run build

  deploy-start:
    runs-on: ubuntu-latest
    environment:
      name: tests
      url: 'calo@tests.com'
    needs: cypress-run
    steps:
      - name: Run build start script
        uses: actions/setup-node@v1
        with:
          start: npm run start
